from BaseClasses import ItemClassification
from typing import TypedDict, List

from BaseClasses import Item


base_id = 268000


class NodebusterItem(Item):
    name: str = "Nodebuster"


class ItemDict(TypedDict):
    name: str
    count: int
    classification: ItemClassification


upgrade_items: List[ItemDict] = [
    { "name": "Damage1", "count": 15 },
{ "name": "Health1", "count": 10 },
{ "name": "SpawnRate1", "count": 15 },
{ "name": "Armor1", "count": 10 },
{ "name": "BitBoost1", "count": 1 },
{ "name": "Size1", "count": 10 },
{ "name": "BossArmor1", "count": 10 },
{ "name": "HealthRegen1", "count": 5 },
{ "name": "NodeFinder1", "count": 5 },
{ "name": "Salvaging1", "count": 5 },
{ "name": "DamagePerEnemy1", "count": 5 },
{ "name": "BossDamage1", "count": 10 },
{ "name": "AttackSpeed1", "count": 1 },
{ "name": "BonusDropChance1", "count": 5 },
{ "name": "ExplodersChance", "count": 1 },
{ "name": "Health2", "count": 8 },
{ "name": "Armor2", "count": 5 },
{ "name": "Lifesteal1", "count": 5 },
{ "name": "Damage2", "count": 10 },
{ "name": "PickupRadius1", "count": 5 },
{ "name": "HealthRegen2", "count": 1 },
{ "name": "Milestones", "count": 1 },
{ "name": "Salvaging2", "count": 1 },
{ "name": "AttackSpeed2", "count": 1 },
{ "name": "SpawnRate2", "count": 1 },
{ "name": "NodeBoost1", "count": 1 },
{ "name": "ArmorPerEnemy1", "count": 10 },
{ "name": "Armor3", "count": 10 },
{ "name": "DropHeal1", "count": 1 },
{ "name": "Health3", "count": 10 },
{ "name": "PulseBolts", "count": 1 },
{ "name": "PulseBoltDamage1", "count": 10 },
{ "name": "PulseBoltCount1", "count": 5 },
{ "name": "ExplodersSize", "count": 5 },
{ "name": "MaxHealthHeal1", "count": 10 },
{ "name": "Armor4", "count": 10 },
{ "name": "BossArmor2", "count": 8 },
{ "name": "Damage3", "count": 10 },
{ "name": "Undamaged1", "count": 6 },
{ "name": "Execute1", "count": 6 },
{ "name": "CritChance1", "count": 10 },
{ "name": "SpawnRate3", "count": 5 },
{ "name": "Armor5", "count": 20 },
{ "name": "Damage4", "count": 3 },
{ "name": "Size2", "count": 1 },
{ "name": "CryptoMine", "count": 1 },
{ "name": "Health4", "count": 10 },
{ "name": "YellowSpawn1", "count": 1 },
{ "name": "Armor6", "count": 30 },
{ "name": "BossDamage2", "count": 10 },
{ "name": "Lifesteal2", "count": 3 },
{ "name": "MovingPulser1", "count": 5 },
{ "name": "Size3", "count": 3 },
{ "name": "MovingPulserSize1", "count": 6 },
{ "name": "MovingPulserAttackSpeed1", "count": 5 },
{ "name": "Health5", "count": 3 },
{ "name": "Lifesteal3", "count": 2 },
{ "name": "MaxHealthToArmor1", "count": 5 },
{ "name": "CritDamage1", "count": 10 },
{ "name": "Damage5", "count": 5 },
{ "name": "Armor7", "count": 5 },
{ "name": "FocusArmor1", "count": 5 },
{ "name": "StealMaxHealth1", "count": 1 },
{ "name": "PulseBoltExplode", "count": 1 },
{ "name": "MovingPulserSize2", "count": 1 },
{ "name": "PulseBoltCount2", "count": 1 },
{ "name": "PulseBoltDamage2", "count": 3 },
{ "name": "MovingPulserSpeed1", "count": 5 },
{ "name": "Undamaged2", "count": 4 },
{ "name": "Execute2", "count": 4 },
{ "name": "MaxHealthHeal2", "count": 5 },
{ "name": "RampingDamage1", "count": 3 },
{ "name": "EnemyDeathPulseBolts", "count": 6 },
{ "name": "SpawnRate4", "count": 5 },
{ "name": "StealMaxHealth2", "count": 1 },
{ "name": "MaxHealthToArmor2", "count": 1 },
{ "name": "RampingArmor1", "count": 5 },
{ "name": "Health6", "count": 5 },
{ "name": "StealMaxHealth3", "count": 1 },
{ "name": "LightningChance1", "count": 5 },
{ "name": "LightningChainCount1", "count": 8 },
{ "name": "LightningDamage1", "count": 8 },
{ "name": "CritDamage2", "count": 8 },
{ "name": "MaxHealthToDamage1", "count": 1 },
{ "name": "Health7", "count": 5 },
{ "name": "Infinity1", "count": 1 },
{ "name": "Infinity2", "count": 1 },
{ "name": "Infinity3", "count": 1 },
{ "name": "Infinity4", "count": 1 },
{ "name": "Infinity5", "count": 1 },
{ "name": "Infinity6", "count": 1 },
{ "name": "Infinity7", "count": 1 },
{ "name": "Infinity8", "count": 1 },
{ "name": "Infinity9", "count": 1 },
{ "name": "Laboratory", "count": 1 },
{ "name": "YellowSpawn2", "count": 1 },
{ "name": "AutoCollect", "count": 8 }
]


act1_items: List[ItemDict] = [
    {'name': "Stinkbug Card",
     'count': 1,
     'classification': ItemClassification.useful},
    {'name': "Stunted Wolf Card",
     'count': 1,
     'classification': ItemClassification.useful},
    {'name': "Wardrobe Key",
     'count': 1,
     'classification': ItemClassification.progression},
    {'name': "Skink Card",
     'count': 1,
     'classification': ItemClassification.useful},
    {'name': "Ant Cards",
     'count': 1,
     'classification': ItemClassification.useful},
    {'name': "Caged Wolf Card",
     'count': 1,
     'classification': ItemClassification.progression},
    {'name': "Squirrel Totem Head",
     'count': 1,
     'classification': ItemClassification.useful},
    {'name': "Dagger",
     'count': 1,
     'classification': ItemClassification.progression},
    {'name': "Film Roll",
     'count': 1,
     'classification': ItemClassification.progression},
    {'name': "Ring",
     'count': 1,
     'classification': ItemClassification.useful},
    {'name': "Magnificus Eye",
     'count': 1,
     'classification': ItemClassification.progression},
    {'name': "Oil Painting's Clover Plant",
     'count': 1,
     'classification': ItemClassification.useful},
    {'name': "Extra Candle",
     'count': 1,
     'classification': ItemClassification.useful},
    {'name': "Bee Figurine",
     'count': 1,
     'classification': ItemClassification.useful},
    {'name': "Greater Smoke",
     'count': 1,
     'classification': ItemClassification.useful},
    {'name': "Angler Hook",
     'count': 1,
     'classification': ItemClassification.useful}
]


filler_items: List[ItemDict] = [
    {'name': "Currency",
     'count': 1,
     'classification': ItemClassification.filler},
    {'name': "Card Pack",
     'count': 1,
     'classification': ItemClassification.filler}
]
